import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "@/components/NavBar";
import ReviewsSection from "@/components/reviews";
import Content from "@/components/content";
import Courses from "@/components/courses";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn("relative h-full font-sans antialiased", inter.className)}
      >
        <main className="relative flex flex-col min-h-screen">
          <NavBar />
          <div className="flex-grow flex-1 mt-10">{children}</div>
          <ReviewsSection className="pt-5 mb-4" />
          <Content />
          <Courses />
        </main>
      </body>
    </html>
  );
}
